### ISSUE TITLE
[libnetwork] Cannot create docker network with a subnet even with a Calico IP Pool Config.

### ISSUE THREAD

**Issue by gcavalcante8808** [projectcalico/libnetwork-plugin#185]
Hi Folks, Im trying to test the calico plugin for docker, but the containers can't use the created networks.
## Expected Behavior

After the IPpool configuration on calico and the network creation on docker, the container creation using calico networks should works flawlessly.

## Current Behavior

Currently, if I try to use a network without a subnet, the following error is returned:

```
docker: Error response from daemon: IpamDriver.RequestAddress: IP assignment error: No configured Calico pools.
```
Following the instructions provided in `https://github.com/projectcalico/calico/issues/1607`, I just created a IPPool, using the following definition:

```
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: test-pool
spec:
  cidr: 172.20.0.0/24
  ipipMode: CrossSubnet
  natOutgoing: true
  disabled: false
```
But the following error occurs when I try to create the network with the command `docker network create --driver calico --ipam-driver calico-ipam --subnet=172.20.0.0/24 bla`:

Error response from daemon: IpamDriver.RequestPool: The requested subnet must match the CIDR of a configured Calico IP Pool.

Looking at the logs available at /var/log/calico/libnetwork/current I have the following information:

time="2018-09-22T16:31:22Z" level=info msg=RequestPool JSON="{"AddressSpace":"CalicoGlobalAddressSpace","Pool":"172.20.0.0/24","SubPool":"","Options":{},"V6":false}" 
time="2018-09-22T16:31:22Z" level=error msg="The requested subnet must match the CIDR of a configured Calico IP Pool."

## Steps to Reproduce (for bugs)

1. Install ETCD and configure calicoctl to use, bootstrapping the calico container with calicoctl node run;
2. In my case the calico node container doesn't shipp libnetwork-plugin, so I just fixed it by downloading the libnetwork-plugin to the container (more info on https://github.com/projectcalico/node/issues/65);
3. Create a ipPool yaml file and submit it to the etcd using calicoctl:
```
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: test-pool
spec:
  cidr: 172.20.0.0/24
  ipipMode: CrossSubnet
  natOutgoing: true
  disabled: false
```
`calicoctl create --filename=./ippool.yml`

4. Create the new network in docker using the command `ocker network create --driver calico --ipam-driver calico-ipam --subnet=172.20.0.0/24 bla`

## Context
I'm trying to do some tests using N docker overlay network plugins.

## Your Environment

* Docker version: 17.06-ce
* Libnetwork-plugin version: 1.1.3
* How you deployed the libnetwork plugin: Download from the releases page directly in the calico-node container.
* Operating System and version: Fedora 28
